# Generated by Django 5.0.3 on 2024-04-12 17:41

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Family_Information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkInformationModel',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('applicationType', models.CharField(choices=[('New', 'New'), ('Renew', 'Renew')], max_length=10)),
                ('passport_no', models.CharField(max_length=20, unique=True)),
                ('country', models.CharField(choices=[('Saudi Arabia', 'Saudi Arabia'), ('Qatar', 'Qatar'), ('United Arab Emirates', 'United Arab Emirates'), ('Malaysia', 'Malaysia'), ('Oman', 'Oman'), ('Kuwait', 'Kuwait'), ('Bahrain', 'Bahrain'), ('Brunei darussalam', 'Brunei darussalam'), ('Seychelles', 'Seychelles'), ('Singapore', 'Singapore'), ('China', 'China'), ('Japan', 'Japan'), ('Hongkong', 'Hongkong'), ('Macau', 'Macau')], max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Work_Information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.FileField(upload_to='images/', validators=[account.models.validate_file_type])),
                ('visa', models.FileField(upload_to='images/', validators=[account.models.validate_file_type])),
                ('embassy_letter', models.FileField(blank=True, null=True, upload_to='images/', validators=[account.models.validate_file_type])),
                ('contract_paper', models.FileField(blank=True, null=True, upload_to='images/', validators=[account.models.validate_file_type])),
                ('driving_license', models.FileField(blank=True, null=True, upload_to='images/', validators=[account.models.validate_file_type])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Documents', to=settings.AUTH_USER_MODEL)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Application', to='account.workinformationmodel')),
            ],
        ),
    ]
