# Generated by Django 5.0.4 on 2024-05-25 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_application_documentsmodel_familydetailmodel_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='old_application', to='account.application')),
                ('documents', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.documentsmodel')),
                ('work_information', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.workinformationmodel')),
            ],
        ),
    ]
