# Generated by Django 5.0.3 on 2024-04-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_familydetailmodel_profilepicmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsmodel',
            name='application_id',
        ),
    ]
