# Generated by Django 5.0.4 on 2024-05-25 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_oldapplicationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldapplicationmodel',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.payment'),
        ),
    ]
