# Generated by Django 5.0.4 on 2024-05-25 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_oldapplicationmodel_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldapplicationmodel',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Old_Application', to=settings.AUTH_USER_MODEL),
        ),
    ]
